# docker run --name dashboard-admin-db -e POSTGRESQL_USERNAME=unisagrado -e POSTGRESQL_PASSWORD=ccomp -e POSTGRESQL_DATABASE=dashboard-admin-db -p 5432:5432 bitnami/postgresql:latest
# run => docker compose up -d

version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=unisagrado
      - POSTGRESQL_PASSWORD=ccomp
      - POSTGRESQL_DATABASE=dashboard-admin-db
